name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Premake
      run: pwsh premake5.bat

    - name: Build ce
      run: make -C ./.build/gmake2 ce

    - name: Build ce-test
      run: make -C ./.build/gmake2 ce-test

    # - name: Test
    #   working-directory: ${{env.SOLUTION_FILE_PATH}}/projects/bin/x64/Release
    #   run: ./ce-test.exe
